### ISSUE TITLE
how use this configs?

### ISSUE THREAD

**Issue by yfjelley** [kyhau/pycharm-configs#1]
but i can not import this configs in pycharm ?
file >> import settings >> 
but error , this is not *.jar ?

**Comment by kyhau** [comment]
This is my PyCharm settings that sync with the Settings Repository plugin.
See https://www.jetbrains.com/help/pycharm/settings-tools-settings-repository.html

1. Install the Settings Repository plugin to your PyCharm
1. During setup, you will be asked to provide a repository URL as your "Settings repository". You can create a new GitHub repository, or if you want to start with my settings then fork my repository to your github account. 
1. Then it will ask you to merge to local or merger to remote.

**Comment by kyhau** [comment]
@yfjelley If you don't have any further question I will close this Issue.
